### ISSUE TITLE
Add support for setting k6build service url in an environment variable

### ISSUE THREAD

**Issue by pablochacin** [grafana/k6exec#30]
In some use cases, such as using k6exec as a replacement for k6 for running tests in k6-operator, there's no control over the command used to invoke it. Therefore it would be convenient to allow setting the URL to the k6build service as an environment variable instead of a CLI option.

**Comment by szkiba** [comment]
This is already supported. The location of the build service can be specified in the `K6_BUILD_SERVICE_URL` environment variable.

README: https://github.com/grafana/k6exec#build-service

code: https://github.com/grafana/k6exec/blob/main/cmd/state.go#L35
